Areas/Admin/Controllers/ProductController.cs
using BookStore.Constant;
using BookStore.Data;
using BookStore.Models;
using BookStore.Repository.IRepository;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleConstant.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var products = _unitOfWork.ProductRepository.GetAll(includedProperties:"Catergory").ToList();
            return View(products);
        }

        

        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> categoryList = _unitOfWork.CategoryRepository.GetAll()
                .Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

            //ViewBag.CategoryList = categoryList;
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = categoryList
            };

            if(id == null || id == 0)
            {
                // Create Product
                return View(productVM);
            }
            else
            {
                // Update Product
                productVM.Product = _unitOfWork.ProductRepository.Get(c => c.Id == id);
                if (productVM.Product == null)
                {
                    return NotFound();
                }
                return View(productVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    if(!string.IsNullOrEmpty(productVM.Product.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, productVM.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productVM.Product.ImageUrl = @"\images\product\" + fileName;
                }

                if(productVM.Product.Id == 0)
                {
                    _unitOfWork.ProductRepository.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.ProductRepository.Update(productVM.Product);
                }

                //_unitOfWork.ProductRepository.Add(productVM.Product);
                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            return View(productVM);
        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Product? productFromDb = _unitOfWork.ProductRepository.Get(c => c.Id == id);
        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(productFromDb);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePost(int? id)
        //{
        //    Product? productFromDb = _unitOfWork.ProductRepository.Get(c => c.Id == id);
        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    _unitOfWork.ProductRepository.Remove(productFromDb);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Product deleted successfully";
        //    return RedirectToAction("Index");
        //}

        #region API
        [HttpGet]
        public IActionResult GetAll()
        {
            var products = _unitOfWork.ProductRepository.GetAll(includedProperties:"Catergory");
            return Json(new {Data = products});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Product? productFromDb = _unitOfWork.ProductRepository.Get(c => c.Id == id);
            if (productFromDb == null)
            {
                return Json( new {success = false, message = "Error while deleting"});
            }
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, productFromDb.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.ProductRepository.Remove(productFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion
    }
}

Areas/Customer/Controllers/CartController.cs
using BookStore.Repository.IRepository;
using BookStore.Utility;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        //public const string SessionCart = "SessionShoppingCart";

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            //return View(GetCartItems());
            return View(SessionService.GetCartItems());
        }

        public IActionResult AddToCart(int productId)
        {
            var product = _unitOfWork.ProductRepository.Get(p => p.Id == productId);
            if (product == null)
            {
                return NotFound("Product not found");
            }

            //var cartItems = GetCartItems();
            var cartItems = SessionService.GetCartItems();
            var existingItem = cartItems.FirstOrDefault(c => c.Product.Id == productId);
            if (existingItem != null)
            {
                existingItem.Quantity++;
            }
            else
            {
                cartItems.Add(new CartItem { Product = product, Quantity = 1 });
            }
            //SaveCartItems(cartItems);
            SessionService.SaveCartItems(cartItems);

            TempData["success"] = "Product added to cart successfully";
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int productId)
        {
            //var cart = GetCartItems();
            var cart = SessionService.GetCartItems();
            var cartItem = cart.FirstOrDefault(c => c.Product.Id == productId);
            if (cartItem != null)
            {
                cart.Remove(cartItem);
            }
            //SaveCartItems(cart);
            SessionService.SaveCartItems(cart);

            TempData["success"] = "Product removed from cart successfully";
            return RedirectToAction("Index");   
        }

        [HttpPost]
        public IActionResult UpdateCart(int productId, int quantity)
        {
            //var cart = GetCartItems();
            var cart = SessionService.GetCartItems();
            var cartItem = cart.FirstOrDefault(c => c.Product.Id == productId);
            if (cartItem != null)
            {
                cartItem.Quantity = quantity;
            }
            //SaveCartItems(cart);
            SessionService.SaveCartItems(cart);
            TempData["success"] = "Cart updated successfully";
            return Ok();
        }

        public IActionResult CheckOut()
        {
            // Logic to proceed to checkout
            TempData["success"] = "Proceeding to checkout";
            return RedirectToAction("CheckOut", "Payment");
        }

        //List<CartItem> GetCartItems()
        //{
        //    List<CartItem> cartItems = new List<CartItem>();
        //    if (HttpContext.Session.GetString(SessionCart) != null)
        //    {
        //        cartItems = JsonConvert.DeserializeObject<List<CartItem>>(HttpContext.Session.GetString(SessionCart));
        //    }
        //    return cartItems;
        //}

        //void ClearCart()
        //{
        //    HttpContext.Session.Remove(SessionCart);
        //}

        //void SaveCartItems(List<CartItem> cartItems)
        //{
        //    HttpContext.Session.SetString(SessionCart, JsonConvert.SerializeObject(cartItems));
        //}
    }
}

Controllers/CategoryController.cs
using BookStore.Data;
using BookStore.Models;
using BookStore.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var categories = _unitOfWork.CategoryRepository.GetAll().ToList();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Catergory category)
        {
            if(category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Display Order can not exactly match the Name");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.CategoryRepository.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Catergory? catergoryFromDb = _unitOfWork.CategoryRepository.Get(c => c.Id == id);
            if (catergoryFromDb == null)
            {
                return NotFound();
            }
            return View(catergoryFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Catergory category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CategoryRepository.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Catergory? catergoryFromDb = _unitOfWork.CategoryRepository.Get(c => c.Id == id);
            if (catergoryFromDb == null)
            {
                return NotFound();
            }
            return View(catergoryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Catergory? catergoryFromDb = _unitOfWork.CategoryRepository.Get(c => c.Id == id);
            if (catergoryFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.CategoryRepository.Remove(catergoryFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using BookStore.Areas.Customer.Controllers;
@inject IHttpContextAccessor HttpContextAccessor

@{
    var session = HttpContextAccessor.HttpContext.Session;
    // string jsonCart = session.GetString(CartController.SessionCart);
    string jsonCart = session.GetString(SessionService.SessionCart);
    if (!string.IsNullOrEmpty(jsonCart))
    {
        var cart = JsonConvert.DeserializeObject<List<CartItem>>(jsonCart);
        <div class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="Cart">Shopping Cart(@cart.Count)</a>
        </div>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.3.0/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.IsInRole(RoleConstant.Role_Admin)) 
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Mangament
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @await Html.PartialAsync("_CartPartial")
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            &copy; 2025 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.3.0/js/dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/y0pvguy0cr8rmdss96klip07fc7vephz9vds1o5sl35j62zf/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')    
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]')
    </script>
}